name: snb

channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib=3.5
  - notebook
  - numpy=1.21
  - pandas=1
  - scikit-learn=1.0
  - scipy=1
  - ipywidgets
  - ipympl
  - pytables
  - pip
  - pillow
  - tqdm
